### PR TITLE
Ensure `make run` can actually run odootools

### PR DESCRIPTION
**Pull request by mhutter**
## Summary

The current make target only loaded `main.go` while some methods are in
other go files.

## Checklist

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog

### CODE REVIEW

**Comment by mhutter** [comment]
@ccremer the preview deployment does not actually work for me, is that on purpose?

**Comment by ccremer** [comment]
> @ccremer the preview deployment does not actually work for me, is that on purpose?

Can you explain further? what exactly doesn't work? error messages?

**Review by ccremer — APPROVED** [review]

**Comment by mhutter** [comment]
> Can you explain further? what exactly doesn't work? error messages?

When trying to create a monthly report, I get

> Oooops
> step 'fetch contracts' failed: decoding result: Odoo Server Error: AccessError Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that: - Human Resources/Manager (Document model: hr.contract)

**Comment by ccremer** [comment]
Well, that's strange... why does your user need additional permissions? :thinking: 
I'll update the deployment so it uses the latest DB dump, maybe that helps

**Comment by mhutter** [comment]
DB dump seems to have fixed the issue, I was able to generate a report from my preview deployment.

**Pull request merged**
